"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { UpdateContex } from "./Store/UpdateContex";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const[role,setrole]=useState("")
  return (
    <html lang="en">
      <body className={inter.className}>
        <UpdateContex.Provider value={{role,setrole}}>{children}</UpdateContex.Provider>
        
        </body>
    </html>
  );
}
